### ISSUE TITLE
USER STORY: Remove users

### ISSUE THREAD

**Issue by domsq** [domsq/the-gamers-forum#12]
As a **site admin** I can **remove users** so that **anyone breaching community standards is removed from the site**

### Acceptance Criteria:
- Admin user will be able to view user accounts under the admin view
- Any users known to be breaching the rules can then be removed following sufficient warning

### Tasks
- [x] Update the admin view to allowing viewing of user accounts
- [x] Update any required templates
- [x] Make any required changes to the admin URL
