### ISSUE TITLE
USER STORY: Update a post

### ISSUE THREAD

**Issue by domsq** [domsq/the-gamers-forum#13]
As a **site user** I can **edit my posts** so that **I can update them if needed**

### Acceptance Criteria:
- User will see a button to click below the post, allowing them to edit it, provided they're the post owner
- The post details will be shown in a form for editing, with the option to then save changes

### Tasks
- [x] Configure view to allow editing of posts
- [x] Create template to display form for post editing
- [x] Update URLs to allow required functionality
