### ISSUE TITLE
USER STORY: Delete a post

### ISSUE THREAD

**Issue by domsq** [domsq/the-gamers-forum#14]
As a **site user** I can **delete my posts** so that **I can remove them if no longer needed**

### Acceptance Criteria:
- User will see a button below the post giving the option to delete it, provided they own the post
- When clicking on delete, they'll be shown a confirmation screen asking if they're sure they want to delete the post

### Tasks
- [x] Create required view to allow deleting of posts
- [x] Configure post detail template as needed
- [x] Update URLs accordingly
