### ISSUE TITLE
USER STORY: Register Account

### ISSUE THREAD

**Issue by domsq** [domsq/the-gamers-forum#2]
As a **site user** I can **register an account** so that **I'm able to use the features reserved for site members**

### Acceptance Criteria:
- The user is able to click on a link to register an account
- The user will be presented with a form to complete to set up a new account

### Tasks
- [x] Install the All-Auth module 
- [x] Configure the required view in Django
- [x] Configure the required template
- [x] Configure the required URL
