### ISSUE TITLE
USER STORY: Manage topics

### ISSUE THREAD

**Issue by domsq** [domsq/the-gamers-forum#9]
As a **site admin** I can **manage the topics shown** so that **I may add to, modify or remove them**

### Acceptance Criteria:
- Admin user will be able to view the topics from the admin page
- Admin user can then modify the topics as required

### Tasks
- [x] Configure the admin view accordingly
- [x] Configure any required templates as needed
- [x] Update the admin URL if required to allow this
